
FROM python:3.10-slim

WORKDIR /app

COPY . /app

RUN apt-get update && apt-get install -y gcc libpq-dev build-essential

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

CMD ["rasa", "run", "--enable-api", "--cors", "*", "--debug"]
